MedicallexiconProject/Controllers/WordController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using AutoMapper;
using DataLayer.Context;
using DomainClasses.Models;
using MedicallexiconProject.Classes.CustomMapper;
using MedicallexiconProject.SecurityModule;
using MedicallexiconProject.ViewModel;
using ServiceLayer.Interfaces;

namespace MedicallexiconProject.Controllers
{
	public partial class WordController : Controller
	{
		private readonly IRelationshipBetweenWords _RelationshipBetweenWordsService;
		private readonly ICategoryService _categoryService;
		private readonly ILanguageService _languageService;
		private readonly IUnitOfWork _uow;
		private readonly IWordService _wordService;

		public WordController(IUnitOfWork uow, IWordService wordService, ICategoryService categoryService,
							  ILanguageService languageService, IRelationshipBetweenWords relationshipBetweenWordsService)
		{
			_wordService = wordService;
			_categoryService = categoryService;
			_languageService = languageService;
			_RelationshipBetweenWordsService = relationshipBetweenWordsService;
			_uow = uow;
		}

		public virtual ActionResult Index(string sort, string sortdir, int? page = 1)
		{
			IList<Word> list = _wordService.GetAll();
			IEnumerable<WordViewModel> model = GetWordViewModels(list);

			return View(model);
		}


		[HttpGet]
		public virtual ActionResult Create(int wordID = 0)
		{
			Word word = _wordService.GetByID(wordID);
			if (word != null)
			{
				var model = new WordViewModel
					{
						Categories = _categoryService.GetSelectList(),
						Languages = _languageService.GetSelectList(),
						WordRelatedID = word.ID,
						WordRelatedName = word.Name
					};
				return View(model);
			}
			else
			{
				var model = new WordViewModel
					{
						Categories = _categoryService.GetSelectList(),
						Languages = _languageService.GetSelectList(),
						WordRelatedID = 0
					};
				return View(model);
			}
		}

		[HttpPost]
		public virtual ActionResult Create(WordViewModel wordViewModel, int wordID = 0)
		{
			var word = new Word();
			Mapper.Map(wordViewModel, word);

			Category category = _categoryService.GetByID(wordViewModel.SelectedCategoryID);
			word.Category = category;

			Language Language = _languageService.GetByID(wordViewModel.SelectedLanguageID);
			word.Language = Language;

			if (ModelState.IsValid)
			{
				_wordService.AddNew(word);
				if (wordID != 0)
				{
					var relationshipBetweenWords = new RelationshipBetweenWords { MainWord = word, RelatedWord = _wordService.GetByID(wordID) };
					_RelationshipBetweenWordsService.AddNew(relationshipBetweenWords);
					_uow.SaveChanges();
					return RedirectToAction(MVC.Word.ActionNames.Index);
				}
				_uow.SaveChanges();
				return RedirectToAction(MVC.Word.ActionNames.CreateRelationshipBetweenWord, new { id = word.ID });
			}
			wordViewModel.Categories = _categoryService.GetSelectList();
			wordViewModel.Languages = _languageService.GetSelectList();
			return View(wordViewModel);
		}


		[HttpPost]
		[AllowUploadSpecialFilesOnly(".jpg,.gif,.png")]
		public virtual ActionResult UploadWordsPicture(HttpPostedFileBase file)
		{
			string fileName = Path.GetFileName(file.FileName);
			string imageFath = "/Uploads/Words/" + fileName;
			if (file.ContentLength > 0 && fileName != null)
			{
				string path = Path.Combine(Server.MapPath("~/Uploads/Words"), fileName);
				file.SaveAs(path);
			}

			return Content("<img src='" + imageFath + "' />");
		}

		public virtual ActionResult Details(int id)
		{
			WordViewModel wordViewModel = CreateWordViewModelByWordID(id);
			return View(wordViewModel);
		}

		public virtual ActionResult GetLanguage(int id)
		{
			IList<Language> language = _RelationshipBetweenWordsService.GetLanguage(id);
			var languageMapper = new LanguageMapper();
			IEnumerable<LanguageViewModel> model = languageMapper.ModelsViewModelsMapping(language);
			return PartialView("_WordLanguages", model);
		}

		[HttpPost]
		public virtual ActionResult Delete(int id)
		{
			_wordService.Delete(id);
			_uow.SaveChanges();
			return RedirectToAction(Index());
		}

		[HttpGet]
		public virtual ActionResult Edit(int id)
		{
			return (null);
		}

		[HttpPost]
		public virtual ActionResult WordInfo(int id)
		{
			WordViewModel wordViewModel = CreateWordViewModelByWordID(id);
			return PartialView(viewName: MVC.Word.Views._WordInfo, model: wordViewModel);
		}

		public virtual ActionResult Search(string query)
		{
			return PartialView(MVC.Word.Views._WordSearch, _wordService.Search(query));
		}

		public virtual ActionResult QuickSearch(string term)
		{
			var word = _wordService.Search(term).
				Select(r => new { label = r.Name });

			return Json(word, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		[OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
		public virtual ActionResult CheckWord(string name, int selectedLanguageID)
		{
			Word word = _wordService.GetWordByWordNameAndLanguageID(name, selectedLanguageID);
			return word.Name != null ? Json(false) : Json(true);
		}

		[HttpGet]
		public virtual ActionResult CreateRelationshipBetweenWord(int id)
		{
			WordViewModel wordViewModel = CreateWordViewModelByWordID(id);
			return View(wordViewModel);
		}

		[HttpPost]
		public virtual ActionResult CreateRelationshipBetweenWord(int mainWordID, int wordID)
		{
			return View();
		}

		private WordViewModel CreateWordViewModelByWordID(int id)
		{
			Word word = _wordService.GetByID(id);
			int relatedCount = _RelationshipBetweenWordsService.GetRelationCount(id);
			WordViewModel wordViewModel = GetWordViewModel(word);
			wordViewModel.RelatedCount = relatedCount;
			return wordViewModel;
		}

		private static WordViewModel GetWordViewModel(Word word)
		{
			var wordMapper = new WordMapper();
			WordViewModel wordViewModel = wordMapper.ModelViewModelMapping(word);
			return wordViewModel;
		}

		private static IEnumerable<WordViewModel> GetWordViewModels(IEnumerable<Word> list)
		{
			var wordMapper = new WordMapper();
			IEnumerable<WordViewModel> WordViewModels = wordMapper.ModelsViewModelsMapping(list);
			return WordViewModels;
		}

		public virtual ActionResult GetWords(string category, string language)
		{
			IEnumerable<Word> words;
			IEnumerable<WordViewModel> wordViewModels;
			if ((!string.IsNullOrEmpty(category) && !string.IsNullOrEmpty(language)))
			{
				words = _wordService.GetWordsByLanguageAndCategory(category, language);
				wordViewModels = GetWordViewModels(words);
				return View("WordList", wordViewModels);
			}
			if (!(string.IsNullOrEmpty(category)))
			{
				words = _wordService.GetAllWordByCategory(category);
				wordViewModels = GetWordViewModels(words);
				return View("WordList", wordViewModels);
			}
			if (!(string.IsNullOrEmpty(language)))
			{
				words = _wordService.GetAllWordByLanguage(language);
				wordViewModels = GetWordViewModels(words);
				return View("WordList", wordViewModels);
			}
			words = _wordService.GetAll();
			wordViewModels = GetWordViewModels(words);
			return View("WordList", wordViewModels);
		}
	}
}

MedicallexiconProject/Views/Word/Create.cshtml
@model MedicallexiconProject.ViewModel.WordViewModel
@{
    ViewBag.Title = "Create";
}

<div class="right">
    @{
        if (Model.WordRelatedID != 0)
        {
        <h3>Create Word for  @Html.ActionLink(Model.WordRelatedName, MVC.Word.ActionNames.WordInfo, new { id = Model.WordRelatedID })</h3>
        }
        else
        {
        <h3>Create Word</h3>
        }
    }
</div>
<p>
    <a href="~/Word" id="btnBack" class="btn btn-group">Back to Word List
    </a>
</p>

@using (Html.BeginForm())
{
    <div>
        @Html.LabelFor(model => model.Name)
    </div>
    <div>
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
    <div>
        @Html.DropDownListFor(x => x.SelectedCategoryID,
                                new SelectList(Model.Categories, "Value", "Text"), "Select Category")
        @Html.DropDownListFor(x => x.SelectedLanguageID,
                                new SelectList(Model.Languages, "Value", "Text"), "Select Language")
    </div>
    <div>
        @Html.LabelFor(model => model.Text)
    </div>
    <div>
        @Html.TextAreaFor(model => model.Text, htmlAttributes: new { style = "width:98%; height:500px" })
        @Html.ValidationMessageFor(model => model.Text)
    </div>

    <div>
    </div>



    <div>
        @Html.LabelFor(model => model.Description)
    </div>
    <div>
        @Html.EditorFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    <p>
        <input type="submit" value="Create" class="btn btn-success" />

    </p>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <link rel="stylesheet" href="~/redactor/css/redactor.css" />

    <script src="~/redactor/redactor.js"> </script>
    <script type="text/javascript">
        $(document).ready(
	        function () {
	            $('#Text').redactor({
	            });
	        }
	    );
    </script>
}

MedicallexiconProject/Views/Word/CreateRelationshipBetweenWord.cshtml
@model MedicallexiconProject.ViewModel.WordViewModel
@{
    ViewBag.Title = "CreateRelationshipBetweenWord";
}

<div class="right">
    <h3>Create Relation Between Word</h3>


</div>
<p>
    <a href="~/Word" id="btnBack" class="btn btn-group">Back to Word List
    </a>
</p>
<h4>Create relation for this word.</h4>
@Html.Partial(partialViewName: MVC.Word.Views._WordInfo, model: Model)
@Html.Partial(MVC.Shared.Views._Search)

MedicallexiconProject/Views/Word/Details.cshtml
@model MedicallexiconProject.ViewModel.WordViewModel
@{
    ViewBag.Title = Model.Name;
}
<div class="right">
    <h3>@Model.Name</h3>
</div>
<p>
    <a href="~/" id="btnBack" class="btn btn-group">Back to Home Page
    </a>
</p>
<div class="container-fluid">
    <div class="row-fluid">

        <div class="span2">
            @Html.Action("GetLanguage", "Word")
        </div>
        <div class="span2">
        </div>
        <div class="span10">
            @Html.Raw(Model.Text)
        </div>
    </div>
</div>

MedicallexiconProject/Views/Word/Index.cshtml
@{
	ViewBag.Title = "Index";
}

@model IEnumerable<MedicallexiconProject.ViewModel.WordViewModel>
@{
	ViewBag.Title = "مدیریت کلمه ها";
}
@Html.Partial(MVC.Word.Views._WordList)

MedicallexiconProject/Views/Word/WordList.cshtml
@{
	ViewBag.Title = "Index";
}

@model IEnumerable<MedicallexiconProject.ViewModel.WordViewModel>
@{
	ViewBag.Title = "مدیریت کلمه ها";
}
@Html.Partial(MVC.Word.Views._WordList)
@section scripts
{
	<script type="text/javascript">
	    $(function() {

	        function LaodWordInfo(id) {
	            showProgress();
	            $.ajax({
	                    type: "Post",
	                    //Just Use URL Action
	                    url: '@Url.Action(MVC.Word.WordInfo())',
	                    data: JSON.stringify({ ID: id }),
	                    contentType: "application/json; charset=utf-8",
	                    dataType: "json",
	                    complete: function(xhr, status) {
	                        var data = xhr.responseText;
	                        if (status === 'error' || !data) {

	                        } else {
	                            var dialog = $("#dialog");
	                            dialog.html(data);
	                            dialog.dialog("open");
	                        }
	                        hideProgress();
	                        return false;
	                    }
	                }
	            );
	        }

	        function showProgress() {
	            $('#Progress').css("display", "block");
	        }

	        function hideProgress() {
	            $('#Progress').css("display", "none");
	        }

	        $(function() {
	            $("#dialog").dialog({
	                autoOpen: false,
	                show: "fade",
	                hide: "fade",
	                width: 550,
	                title: "WordInfo",
	                resizable: false
	            });
	        });
	    });
	</script>
}

MedicallexiconProject/Views/Word/_DeleteWord.cshtml
<h3>Are you sure you want to delete this?</h3>
<input type="submit" value="Delete" />
|

MedicallexiconProject/Views/Word/_WordInfo.cshtml
@model MedicallexiconProject.ViewModel.WordViewModel
<table class="table table-bordered">
	<tr>
	<th>@Html.DisplayNameFor(model => model.Name)</th>
	<th>@Html.DisplayNameFor(model => model.Description)</th>
	<th>@Html.DisplayNameFor(model => model.CategoryName)</th>
	<th>@Html.DisplayNameFor(model => model.RelatedCount)</th>
	<tr />
	<tr>
		<td>
			@Html.DisplayFor(model => model.Name)
		</td>
		<td>
			@Html.DisplayFor(model => model.Description)
		</td>
		<td>
			@Html.DisplayFor(model => model.CategoryName)
		</td>	
        <td>
			@Html.DisplayFor(model => model.RelatedCount)
		</td>
	</tr>
</table>

MedicallexiconProject/Views/Word/_WordLanguages.cshtml
@model IEnumerable<MedicallexiconProject.ViewModel.LanguageViewModel>
@{
	ViewBag.Title = "_WordLanguages";
}

<h2>Language</h2>


@foreach (var item in Model)
{
    <ul>
        <li>@item.Name</li>
    </ul>
}

MedicallexiconProject/Views/Word/_WordList.cshtml

	<script type="text/javascript">
	
	        function LaodWordInfo(id) {
	            showProgress();
	            $.ajax({
	                    type: "Post",
	                    //Just Use URL Action
	                    url: '@Url.Action(MVC.Word.WordInfo())',
	                    data: JSON.stringify({ ID: id }),
	                    contentType: "application/json; charset=utf-8",
	                    dataType: "json",
	                    complete: function(xhr, status) {
	                        var data = xhr.responseText;
	                        if (status === 'error' || !data) {

	                        } else {
	                            var dialog = $("#dialog");
	                            dialog.html(data);
	                            dialog.dialog("open");
	                        }
	                        hideProgress();
	                        return false;
	                    }
	                }
	            );
	        }

	        function showProgress() {
	            $('#Progress').css("display", "block");
	        }

	        function hideProgress() {
	            $('#Progress').css("display", "none");
	        }

	        $(function() {
	            $("#dialog").dialog({
	                autoOpen: false,
	                show: "fade",
	                hide: "fade",
	                width: 550,
	                title: "WordInfo",
	                resizable: false
	            });
	        });

	</script>


@using System.Globalization

@helper WebGridPageFirstItem(WebGrid grid)
{ @(((grid.PageIndex + 1)*grid.RowsPerPage) - (grid.RowsPerPage - 1)) }
@helper WebGridPageLastItem(WebGrid grid)
{
	if (grid.TotalRowCount < (grid.PageIndex + 1*grid.RowsPerPage))
	{
		@grid.TotalRowCount
	}
	else
	{
		@((grid.PageIndex + 1)*grid.RowsPerPage)
	}
}
<div class="right">
	<h3>Words List</h3>


</div>
<p>
	<a href="~/" id="btnBack" class="btn btn-group">Back to Home Page
	</a>
	<a href="~/Word/Create" id="btnCreateWord" class="btn btn-success">Create Word
	</a>
</p>
@{
	var grid = new WebGrid(
		source: Model,
		canPage: true,
		rowsPerPage: 10,
		canSort: true,
		defaultSort: "Word"
		);
	int rowIndex = ((grid.PageIndex + 1)*grid.RowsPerPage) - (grid.RowsPerPage - 1);
}
<div id="container" dir="rtl">
	@grid.GetHtml(
		tableStyle: "table table-striped table-bordered table-condensed",
		htmlAttributes: new {id = "MyGrid"},
		mode: WebGridPagerModes.All,
		columns:
			grid.Columns(
				grid.Column(header: "",
				            style: "text-align-center-col",
				            columnName: "#",
				            format: @<text>@(rowIndex++)</text>),
				grid.Column(header: "کلمه",
				            columnName: "Word",
				            style: "text-align-center-col"
				            , format: @<span style="font-weight: bold">@item.Name</span>
					),
				grid.Column(header: "زبان",
				            columnName: "Language",
				            style: "text-align-center-col"
				            , format: @<span style="font-weight: bold">@item.LanguageName</span>
					),
				grid.Column(header: "دسته بندی",
				            columnName: "Category",
				            style: "text-align-center-col"
				            , format: @<span style="font-weight: bold">@item.CategoryName</span>
					),
				grid.Column(header: "تاریخ",
				            style: "text-align-center-col",
				            columnName: "Date",
				            format: item =>
								{
									int ym = item.CreatedDate.Year;
									int mm = item.CreatedDate.Month;
									int dm = item.CreatedDate.Day;
									var persianCalendar = new PersianCalendar();
									int ys = persianCalendar.GetYear
										(new DateTime(ym, mm, dm, new GregorianCalendar()));
									int ms = persianCalendar.GetMonth
										(new DateTime(ym, mm, dm, new GregorianCalendar()));
									int ds = persianCalendar.GetDayOfMonth
										(new DateTime(ym, mm, dm, new GregorianCalendar()));
									return ys + "/" + ms.ToString("00") + "/" + ds.ToString("00");
								}
					),
				grid.Column(header: "",
				            style: "text-align-center-col",
				            format: item => @Html.ActionLink
					                            (linkText: "Edit",
					                             actionName: "Edit",
					                             controllerName: "Word",
					                             routeValues: new {id = item.Id},
					                             htmlAttributes: new {@class = "btn btn-group"})),
				grid.Column(
					format: @<a  class="btn btn-group " onclick="LaodWordInfo(@item.ID) "  >Details</a>),
				grid.Column(header: "",
				            style: "text-align-center-col",
				            format: item => @Html.ActionLink
					                            (linkText: "Delete",
					                             actionName: "Delete",
					                             controllerName: "Word",
					                             routeValues: new {id = item.Id},
					                             htmlAttributes: new {@class = "btn btn-group"}))
			)
		       )
	<strong>Page:</strong> @(grid.PageIndex + 1)
	/ @grid.PageCount, <strong>Records:</strong> @WebGridPageFirstItem(@grid) - @WebGridPageLastItem(@grid)
	of @grid.TotalRowCount
</div>
<div id="WordInfo">
</div>
<div id="Progress" style="display: none">
	<img src="@Url.Content("~/Images/loading.gif")" alt="loading..."  />
</div>

<div id="dialog" class="modal-body" dir="rtl">
</div>

MedicallexiconProject/Views/Word/_WordSearch.cshtml
@using DomainClasses.Models
@using MedicallexiconProject.Helpers
@model IEnumerable<Word>

<table class="table table-striped table-bordered table-condensed" dir="rtl">

    <tr class="webgrid-header">

        <th style="text-align: center">Check</th>

        <th style="text-align: center">ID
        </th>
        <th style="text-align: center">Word
        </th>
        <th style="text-align: center">Language
        </th>
        <th style="text-align: center">Category
        </th>
    </tr>
    @{
        int x = 0;
    }
    @foreach (Word item in Model)
    {
        <tr>
            <td style="text-align: center; width: 35px;">
                <input type='checkbox' name='@item.ID'  />
            </td>

            <td style="text-align: center">
                <span class="badge badge-info">@Html.Raw(++x)</span>
            </td>
            <td style="text-align: center">
            @Html.ActionLink(linkText: item.Name, result: MVC.Word.Details(item.ID).AddRouteValue("name", item.Name.ToSeoUrl()))
            <td style="text-align: center">
                @item.Language.Name
            </td>
            <td style="text-align: center">
                @item.Category.Name
            </td>
        </tr>
    }
</table>